//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginHelper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class pluginHelper : global::System.Configuration.ApplicationSettingsBase {
        
        private static pluginHelper defaultInstance = ((pluginHelper)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pluginHelper())));
        
        public static pluginHelper Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ap-bglr-fsei.internal.sungard.corp\\CFS\\Ambit Asset Finance\\Himadri\\PluginHelper" +
            "")]
        public string NetworkPathForTemplateCollection {
            get {
                return ((string)(this["NetworkPathForTemplateCollection"]));
            }
            set {
                this["NetworkPathForTemplateCollection"] = value;
            }
        }
    }
}
